OPENAI_API_KEY = "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"
DB_NAME = "chatbot"
DB_USER = "postgres"
DB_PASSWORD = "your_db_password_here"
DB_HOST = "localhost"
ADMIN_PASSWORD = "admin123"
